### ISSUE TITLE
Improving Sign In page

### ISSUE THREAD

**Issue by poojaramnaney** [MonalikaPatnaik/UMatter#136]
changing the UI and making it more appealing especially the "forgot password?" text. Please assign m e this issue under GSSOC'23.

**Comment by chirayu-humar** [comment]
in this sign in page, i observed that page is not properly responsive actually when we reduce the width of page using developer tools the possition of the icon of "invisible password" changes abnormally and in smart phone view the icon is  not visible because it is getting misplaced i can solve that issue using css **flex box properties** and _media queries_ .

**Comment by MonalikaPatnaik** [comment]
Hey @poojaramnaney, i think the ui of signin page is being assigned to someone else..
Also, @chirayu-humar similar issue is already been assigned: #123
