### ISSUE TITLE
making sign up part of navbar working which is along services part

### ISSUE THREAD

**Issue by anshikkay** [MonalikaPatnaik/UMatter#158]
![Screenshot (105)](https://github.com/MonalikaPatnaik/UMatter/assets/129502224/dffb8ef8-0ede-4112-8959-126b49250578)

**Comment by anshikkay** [comment]
sign up which is showing in blue in my screenshot isn't working and it is not directing the web page to sign up page. i want to contribute on this part

**Comment by chirayu-humar** [comment]
i am able make a good front-end of sign up page, i can also link this with your data base so that you people can collect all data which is filled by user in sign up form. i will use react js as technology and will try not to disturb your existing code, i will make a seprate file and will link that to "href" attribute of  sign up anchor tag. 

i observed that there were no data base files in your code, the front-end will match with the theme of existing website and after submition of form all the filled data will be sent back to the server in JSON format which can be then easity saved in any data base

**Comment by MonalikaPatnaik** [comment]
Hryy..sign-up page is already been assigned: #12
