### ISSUE TITLE
Close button in navbar

### ISSUE THREAD

**Issue by Soulpurr** [MonalikaPatnaik/UMatter#436]
**Describe the bug**
Close button is not there in mobile navbar 

**Screenshort**
![Screenshot_2023-05-27-16-02-20-04_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MonalikaPatnaik/UMatter/assets/92094765/a4d3d01f-7725-4afa-aefe-7128a8bf2ae9)

**Comment by Piyusharora2003** [comment]
![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/0dde30f4-997d-4afb-a0d0-fe727badc79f)
![image](https://github.com/MonalikaPatnaik/UMatter/assets/74443858/f81acdbe-6b40-43b8-b686-3f463368c4cd)
Resolved but knowingly could not find the perfect x mark in the library

**Comment by MonalikaPatnaik** [comment]
Hey @Piyusharora2003..don't create a PR until it is being assigned it to you! We cann't merge it..it's against the rules..Since you created the PR unknowingly, I am assigning this issue to you!
As @Soulpurr raised the issue first, ideally he needs to contribute...So, @Soulpurr i am assigning this issue to you too..What you can do is add the sign in sign up option in the mobile navbar..since it's not there..Are u willing to do it??If yes, then submit your PR sooon...

**Comment by Soulpurr** [comment]
Okk I will submit it by tomorrow

**Comment by Piyusharora2003** [comment]
sorry i don't know anything about that. i am not a part of gssoc .
