### ISSUE TITLE
Attend Workshop page 

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [MonalikaPatnaik/UMatter#46]
hey, Monalika I want to contribute under GSSOC 23 and Complete the Workshop page please Assign this to me.

**Comment by Mansi168** [comment]
you are assigned @i-am-SnehaChauhan go ahead!

**Comment by Mansi168** [comment]
you are assigned @i-am-SnehaChauhan !

**Comment by Suchitra-Sahoo** [comment]
@Mansi168 may I work on this issue as a GSoC'23 Contributor too?

**Comment by Mansi168** [comment]
It is already assigned :(

**Comment by Prajwal0225** [comment]
@MonalikaPatnaik and @Mansi168 This issue is pending for a long time can you assign this to me I wanted to work on this issue 


### Add ScreenShots

Here are some rough visual references to give an idea of what I am going to build

- Home Page 
![1-home](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/d7492867-2bae-4116-aaab-cdc760f9c768)


- WorkShop section to get information about various workshop 
![WorkShop](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/575fe401-77c5-44cb-a9f0-567315963a18)


- Workshop Schedules
![WorkShop-Shedule](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/d9d1a924-075d-4c72-8424-d616a3d92851)


- Form to book a slot for a workshop
![form to book a slot](https://github.com/MonalikaPatnaik/UMatter/assets/103810119/081af11f-03da-496c-96ef-ae09f6ac8ec9)
